# Generated by Django 3.2.4 on 2021-06-22 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=200)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
