# Generated by Django 3.2.4 on 2021-06-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_school', '0003_auto_20210625_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='app_school/school/'),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='app_school/school_admin/'),
        ),
    ]
